### ISSUE TITLE
revalee.sageanalytic.com is down

### ISSUE THREAD

**Issue by sepehr1014** [SageAnalytic/Revalee#5]
This library is great. I had the exact same idea and after some research, I found Revalee and started planning to use it. Now that I've finally found the time to work on this feature we need, revalee.sageanalytic.com seem to be down.

By the way you haven't worked on this project for over a year and a half. Does that mean it has no bug/flaws or have you discontinued supporting this project?

Thanks in advance,
Sepehr

**Comment by BrianMullin** [comment]
Thanks, Sepehr.

I apologize for the delay. Our web and mail server experienced a double hard drive failure and had to be rebuilt.

The project has not needed any updates lately. However, it is still used in our production services.

**Comment by sepehr1014** [comment]
Thank you Brian
